name = "glatch"
version = "1.1.1"
description = "Gleam type check using pattern matching"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glatch" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gledo = ">= 1.0.1"
gluple = ">= 1.1.0"

[dev-dependencies]
cleam = ">= 1.5.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
